### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by winston0410** [winston0410/camouflage#13]
Documentations need to cover the following areas, with reference from `nano-css`

`create()`
https://github.com/streamich/nano-css/blob/master/docs/Installation.md

`rule()`
https://github.com/streamich/nano-css/blob/master/docs/rule.md

`prefixer()`
https://github.com/streamich/nano-css/blob/master/docs/prefixer.md

`keyframe()`
https://github.com/streamich/nano-css/blob/master/docs/keyframes.md

`virtual()`
API for this is slight different, see source for reference
https://github.com/streamich/nano-css/blob/master/docs/virtual.md

`hydration()`
https://github.com/streamich/nano-css/blob/master/docs/hydrate.md

Server side rendering

**Comment by joelamltc** [comment]
Helping hand is here

**Comment by winston0410** [comment]
Thank you @joelamltc! How about you try rewriting the `installation.md`, which can be find in `./docs/`. You will need to check `./src/index.js` to check the accepted parameters, as some parameters available in `nano-css` has been removed.
