### ISSUE TITLE
Improve performance for nesting()

### ISSUE THREAD

**Issue by winston0410** [winston0410/camouflage#9]
Currently no check is made to check if `,` or `&` exists in the className of styles to be created by `renderer.put`, which should be done in order to improve performance of this add on.

https://github.com/winston0410/camouflage/blob/6fd423b2eb3228fa2ada87699f5430f7874dcc30/src/addon/nesting.js#L2-L16

**Comment by ych605** [comment]
how to check the performance?

**Comment by winston0410** [comment]
You need create a benchmark in `./benchmarks` and test the improved version.
